#!/bin/bash

setup_wizard() {
    setup_welcome
    setup_project
    setup_source
    setup_destination
    setup_ssh
    setup_confirm
    setup_write_config
    setup_done
}

setup_welcome() {
    section "PROJECT PHOENIX SETUP"

    echo
    echo "Welcome to Project Phoenix."
    echo
    echo "Rise. Recover. Restore."
    echo
    echo "This wizard will configure your first backup."
    echo
    read -rp "Press ENTER to continue..."
}

setup_project() {
    echo
    section "PROJECT"

    read -rp "Project name [Project Phoenix]: " SETUP_PROJECT_NAME
    SETUP_PROJECT_NAME="${SETUP_PROJECT_NAME:-Project Phoenix}"
}

setup_source() {
    echo
    section "SOURCE"

    echo "What would you like to protect?"
    echo
    echo "1) Docker"
    echo "2) Custom folder"
    echo

    read -rp "Selection [1]: " SETUP_SOURCE_TYPE
    SETUP_SOURCE_TYPE="${SETUP_SOURCE_TYPE:-1}"

    if [ "$SETUP_SOURCE_TYPE" = "1" ]; then
        read -rp "Docker folder [/volume2/docker/]: " SETUP_SOURCE
        SETUP_SOURCE="${SETUP_SOURCE:-/volume2/docker/}"
    else
        read -rp "Source folder: " SETUP_SOURCE
    fi
}

setup_destination() {
    echo
    section "DESTINATION"

    read -rp "Backup host [backup-server.local]: " SETUP_BACKUP_HOST
    SETUP_BACKUP_HOST="${SETUP_BACKUP_HOST:-backup-server.local}"

    read -rp "Backup user [backup]: " SETUP_BACKUP_USER
    SETUP_BACKUP_USER="${SETUP_BACKUP_USER:-backup}"

    read -rp "Destination path [/mnt/backups/project-phoenix/]: " SETUP_DESTINATION
    SETUP_DESTINATION="${SETUP_DESTINATION:-/mnt/backups/project-phoenix/}"
}

setup_ssh() {
    echo
    section "SSH"

    read -rp "SSH key location [/home/$USER/.ssh/id_ed25519]: " SETUP_SSH_KEY
    SETUP_SSH_KEY="${SETUP_SSH_KEY:-/home/$USER/.ssh/id_ed25519}"
}

setup_confirm() {
    echo
    section "SUMMARY"

    echo "Project Name : $SETUP_PROJECT_NAME"
    echo "Source       : $SETUP_SOURCE"
    echo "Backup Host  : $SETUP_BACKUP_HOST"
    echo "Backup User  : $SETUP_BACKUP_USER"
    echo "Destination  : $SETUP_DESTINATION"
    echo "SSH Key      : $SETUP_SSH_KEY"
    echo
    read -rp "Write config.conf with these settings? [Y/n]: " SETUP_CONFIRM
    SETUP_CONFIRM="${SETUP_CONFIRM:-Y}"

    case "$SETUP_CONFIRM" in
        Y|y|YES|yes)
            ;;
        *)
            echo
            echo "Setup cancelled. No configuration was written."
            exit 0
            ;;
    esac
}

setup_write_config() {
    CONFIG_FILE="$PROJECT_ROOT/config.conf"

    if [ -f "$CONFIG_FILE" ]; then
        BACKUP_FILE="$PROJECT_ROOT/config.conf.backup.$(date +%Y%m%d-%H%M%S)"
        cp "$CONFIG_FILE" "$BACKUP_FILE"
        log_warning "Existing config.conf backed up to: $BACKUP_FILE"
    fi

    cat > "$CONFIG_FILE" <<EOF
# Project Phoenix Configuration
# Generated by phoenix setup
# Generated: $(date)

PROJECT_NAME="$SETUP_PROJECT_NAME"
TAGLINE="Rise. Recover. Restore."

SOURCE="$SETUP_SOURCE"
DESTINATION="$SETUP_DESTINATION"

BACKUP_HOST="$SETUP_BACKUP_HOST"
BACKUP_USER="$SETUP_BACKUP_USER"

SSH_KEY="$SETUP_SSH_KEY"

BACKUP_DIR="$PROJECT_ROOT"
EXCLUDE_FILE="$PROJECT_ROOT/exclude.txt"
EOF

    log_success "Configuration written: $CONFIG_FILE"
}

setup_done() {
    echo
    section "SETUP COMPLETE"

    echo "Project Phoenix is configured."
    echo
    echo "Next recommended command:"
    echo
    echo "  bash scripts/phoenix.sh check-config"
    echo
    echo "Then:"
    echo
    echo "  bash scripts/phoenix.sh backup"
    echo
}